In [1]:
%pip show numpy

Name: numpy
Version: 1.24.4
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: d:\systemenvironment\anaconda3\envs\mlgz\lib\site-packages
Requires: 
Required-by: contourpy, matplotlib, pandas, scikit-learn, scipy, seaborn
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.4'

# 基础性探索

## 对比numpy与原生python的性能对比

In [4]:
n = 1000000

In [5]:
%%timeit
# python原生
x = [i for i in range(n+1)] # list列表
sum_x = 0
for i in x:
    sum_x += i**2
sum_x

432 ms ± 12.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%%timeit
# numpy实现
# x = np.array([i for i in range(n+1)]) # nd array数组  向量矩阵
x = np.arange(n+1)
np.sum(x**2)

10.7 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


# 核心对象：ndarray

创建数组：np.array()、全零(2)、全一(2)、指定数值(2)、空数组(2)  
等差数组：arange、linspace  
改变形状：reshape  
随机数组：random()、rand()、randint()、randn()、normal()\uniform()、seed()  
查看文档：?、help()

## 创建

In [7]:
# 创建一维数组
a = np.array([1,2,3,4,5,6])
a # 向量

array([1, 2, 3, 4, 5, 6])

In [8]:
# 创建二维数组
A = np.array([ [1,2,3], 
              [4,5,6], 
              [7,8,9]])
A # 矩阵

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 属性

In [9]:
# ndim维度数量
print(a.ndim) 
print(A.ndim)

1
2


In [10]:
# shape形状 维度
print(a.shape)
print(A.shape) # 3行3列

(6,)
(3, 3)


In [11]:
# size元素个数
print(a.size)
print(A.size)

6
9


In [12]:
# dtype元素类型
print(a.dtype)
print(A.dtype)

int32
int32


## 便捷创建ones

In [13]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(8).dtype # 默认创建浮点型

dtype('float64')

In [15]:
np.ones(shape=(2,4), dtype='int64') # shape  dtype

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [16]:
np.ones_like(A) # 创建形状相同的数组

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## 便捷创建zeros

In [17]:
np.zeros((3,2), dtype='int64')

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [18]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 指定数值创建full

In [19]:
np.full(8,666) # 指定数组形状  指定数组数值

array([666, 666, 666, 666, 666, 666, 666, 666])

In [20]:
np.full((2,4), 1043)

array([[1043, 1043, 1043, 1043],
       [1043, 1043, 1043, 1043]])

In [21]:
np.full_like(A,374)

array([[374, 374, 374],
       [374, 374, 374],
       [374, 374, 374]])

## 创建空数组empty：元素随机值

In [33]:
np.empty(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.empty((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.empty_like(A)

array([[         0,          1,          0],
       [       441,       1264,          0],
       [       768,        441, 1369109312]])

## 创建等差数组arange

In [34]:
np.arange(10) # 包前不包后

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(1,10,2) # 开始 结束 步长

array([1, 3, 5, 7, 9])

In [38]:
np.arange(10).reshape(2,5) # 改变形状reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 创建等差数组linspace

In [40]:
np.linspace(0,10,5) # 起始 终止(包含) 个数

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## 创建随机数数组random

In [42]:
np.random.random() # 0到1的随机数 不包含1

0.4237240334722222

In [43]:
np.random.random(5) # 5个

array([0.24536128, 0.99126585, 0.0612808 , 0.15163629, 0.50203532])

In [46]:
np.random.random((2,4)) # 2行4列 传元组

array([[0.26197514, 0.33291841, 0.38479245, 0.4782498 ],
       [0.28185954, 0.74538219, 0.02322522, 0.33492452]])

## 创建随机数数组rand

In [47]:
np.random.rand()

0.30428730845876384

In [48]:
np.random.rand(5)

array([0.74656883, 0.99705106, 0.71720804, 0.66429319, 0.79707596])

In [49]:
np.random.rand(2,3) # 不用传元组

array([[0.89837031, 0.54724053, 0.62741366],
       [0.60254325, 0.61442833, 0.75399601]])

In [50]:
np.random.rand(2,3,4)

array([[[0.84097193, 0.42364063, 0.03732786, 0.69965144],
        [0.95863207, 0.63960309, 0.1057799 , 0.82032251],
        [0.48879353, 0.74086251, 0.32329497, 0.0482025 ]],

       [[0.21718297, 0.66494739, 0.86137497, 0.59808986],
        [0.88507105, 0.87152339, 0.56312289, 0.96841537],
        [0.81501562, 0.42395778, 0.34107568, 0.68069834]]])

## 创建随机整数数组randint

In [51]:
np.random.randint(5) # 0到5间的随机数 不包后

4

In [53]:
np.random.randint(3,10) # 3到10的随机数 不包后

9

In [56]:
np.random.randint(3,10,size=4) # 4个

array([7, 7, 8, 6])

In [69]:
np.random.randint(3,10,(2,3)) # 2行3列

array([[4, 9, 7],
       [8, 6, 9]])

## 随机种子seed(调试-每次随机结果一样)

In [72]:
np.random.seed(656)
np.random.randint(3,10,(2,3))

array([[6, 8, 3],
       [9, 9, 6]])

## 具有标准正态分布的随机数randn

In [73]:
np.random.randn(5)

array([-0.02872151, -1.55623571,  0.03968569,  0.32836457,  1.42258494])

In [74]:
np.random.randn(5,2)

array([[ 0.71060724,  0.02349468],
       [-0.79349136,  0.02462305],
       [-0.22906072, -0.5357155 ],
       [ 0.6747294 ,  0.71785838],
       [ 1.42192423, -1.335596  ]])

In [75]:
np.random.randn(2,4,2)

array([[[ 0.02292897,  0.86992308],
        [-0.63883041, -0.57392423],
        [-0.35826868,  1.31647355],
        [-1.33034621, -1.11902429]],

       [[ 0.3824148 ,  0.34870556],
        [-0.18834013,  0.80505674],
        [-0.74605918, -0.63896701],
        [ 0.47667375,  0.54318413]]])

## 具有高斯分布的随机数据normal(可设均值方差)

In [76]:
np.random.normal() # 默认均值0 方差1 标准正态分布

0.319617401504003

In [80]:
np.random.normal(10,1000,4) # 5个 

array([ 381.35193597, -639.92699048,   27.96971324,  421.90173928])

In [81]:
np.random.normal(10,1000,size=(2,4))

array([[  801.48719548,  -593.03072474,   781.91478282,  -341.23514008],
       [ 1132.01450909, -2252.22531118,  -386.48885445,   -10.48770378]])

## 具有均匀分布的随机数据uniform

In [82]:
np.random.uniform() # 默认0到1的随机数 不包后

0.1317830661080962

In [84]:
np.random.uniform(1,5) # 1到5的随机数

3.074745019511131

In [85]:
np.random.uniform(1,5,size=(3,4)) # 3行4列

array([[1.35280612, 1.02290308, 2.610166  , 1.15536378],
       [1.55888252, 1.23378518, 2.15296581, 3.64262604],
       [1.86923099, 4.01302336, 2.78760738, 2.12483152]])

## 查看说明

In [93]:
np.random.uniform?

In [94]:
help(np.random.uniform)

Help on built-in function uniform:

uniform(...) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    .. note::
        New code should use the `~numpy.random.Generator.uniform`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than or equal to high

# 索引和切片

In [95]:
a = np.arange(10) # 一维数组 向量
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
A = np.arange(20).reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 一维数组

In [99]:
print(a)
print(a[0])
print(a[4])
print(a[-1]) # 倒数第一个

[0 1 2 3 4 5 6 7 8 9]
0
4
9


In [102]:
print(a[0:5]) # 索引0到索引5(不包括)
print(a[:5]) # 到索引5(不包括)
print(a[4:]) # 索引4到
print(a[-3:]) # 倒数第三个到
print(a[:]) # 到

[0 1 2 3 4]
[0 1 2 3 4]
[4 5 6 7 8 9]
[7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [103]:
print(a[::-1]) # 倒叙 ::-1

[9 8 7 6 5 4 3 2 1 0]


## 二维数组

In [108]:
print(A[0,0]) # 0行0列
print(A[0,:]) # 0行 列(所有)
print(A[0]) # 0行
print(A[-1]) # -1行
print(A[:,0]) # 0列 行(所有)
print(A[:,-1]) # -1列 行(所有)
print(A[:2,:4]) # 2行4列  到

0
[0 1 2 3 4]
[0 1 2 3 4]
[15 16 17 18 19]
[ 0  5 10 15]
[ 4  9 14 19]
[[0 1 2 3]
 [5 6 7 8]]


In [107]:
print(A[::-1,::-1]) # 倒叙 行列

[[19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


## np切片(引用绑定)

In [109]:
X = A[:2,:3]
X

array([[0, 1, 2],
       [5, 6, 7]])

In [110]:
X[0,0] = 666
X

array([[666,   1,   2],
       [  5,   6,   7]])

In [111]:
A

array([[666,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

## np切片(引用绑定)

In [112]:
A[0,0] = 0
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
X

array([[0, 1, 2],
       [5, 6, 7]])

## 拷贝(不关联)

In [114]:
X = A[:2,:3].copy()
X

array([[0, 1, 2],
       [5, 6, 7]])

In [115]:
X[0,0] = 666
X

array([[666,   1,   2],
       [  5,   6,   7]])

In [116]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 合并和拆分

## 合并concatenate

In [124]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
a = np.array([6]*4)
a

array([6, 6, 6, 6])

In [131]:
np.concatenate((X,a)) # a是列向量

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [135]:
A = np.concatenate((X,a.reshape(1,4))) # 把a变成行向量
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

## 合并vstack

In [136]:
np.vstack((X,a)) # vstack

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

## 合并hstack

In [137]:
B = np.full((3,2),666)
B

array([[666, 666],
       [666, 666],
       [666, 666]])

In [138]:
np.hstack((X,B)) # hstack

array([[  0,   1,   2,   3, 666, 666],
       [  4,   5,   6,   7, 666, 666],
       [  8,   9,  10,  11, 666, 666]])

In [139]:
np.concatenate((X,B),axis=1) # concatenate参数axis

array([[  0,   1,   2,   3, 666, 666],
       [  4,   5,   6,   7, 666, 666],
       [  8,   9,  10,  11, 666, 666]])

## 拆分split

In [140]:
np.split(X,[-1],axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [143]:
X1,X2 = np.split(X,[-1],axis=1)
print(X1)
print(X2)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 3]
 [ 7]
 [11]]


## 拆分vsplit

In [144]:
np.vsplit(X,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [145]:
X1,X2,X3 = np.hsplit(X,[1,3])
print(X1)
print(X2)
print(X3)

[[0]
 [4]
 [8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3]
 [ 7]
 [11]]


# 矩阵运算

## python的list和nparray对比

In [151]:
# python的列表
x = [i for i in range(5)]
print(x)
print(x*2)
print(x+x)

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


In [157]:
%%time
n = 5000000
x = [i for i in range(n)]
y = [i * 2 for i in x]

CPU times: total: 281 ms
Wall time: 919 ms


In [159]:
# np的arr
X = np.arange(5)
print(X)
print(X*2)
print(X+X)

[0 1 2 3 4]
[0 2 4 6 8]
[0 2 4 6 8]


In [160]:
%%time 
n = 5000000
X = np.arange(n)
Y = X * 2

CPU times: total: 0 ns
Wall time: 15.1 ms


In [161]:
Y[:10]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## 一元运算

In [169]:
X = np.arange(-6, 6, 0.5).reshape(4, 6)
X

array([[-6. , -5.5, -5. , -4.5, -4. , -3.5],
       [-3. , -2.5, -2. , -1.5, -1. , -0.5],
       [ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5]])

In [196]:
print(np.abs(X)) # 绝对值
print(np.sqrt(X[2:,:])) # 平方根
print(np.square(X)) # 平方

[[6.  5.5 5.  4.5 4.  3.5]
 [3.  2.5 2.  1.5 1.  0.5]
 [0.  0.5 1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5 5.  5.5]]
[[0.         0.70710678 1.         1.22474487 1.41421356 1.58113883]
 [1.73205081 1.87082869 2.         2.12132034 2.23606798 2.34520788]]
[[36.   30.25 25.   20.25 16.   12.25]
 [ 9.    6.25  4.    2.25  1.    0.25]
 [ 0.    0.25  1.    2.25  4.    6.25]
 [ 9.   12.25 16.   20.25 25.   30.25]]


In [195]:
print(np.exp(X)) # e**x
print(np.log2(X[3:,:])) # logx
print(np.log10(X[3:,:])) # logx

[[2.47875218e-03 4.08677144e-03 6.73794700e-03 1.11089965e-02
  1.83156389e-02 3.01973834e-02]
 [4.97870684e-02 8.20849986e-02 1.35335283e-01 2.23130160e-01
  3.67879441e-01 6.06530660e-01]
 [1.00000000e+00 1.64872127e+00 2.71828183e+00 4.48168907e+00
  7.38905610e+00 1.21824940e+01]
 [2.00855369e+01 3.31154520e+01 5.45981500e+01 9.00171313e+01
  1.48413159e+02 2.44691932e+02]]
[[1.5849625  1.80735492 2.         2.169925   2.32192809 2.45943162]]
[[0.47712125 0.54406804 0.60205999 0.65321251 0.69897    0.74036269]]


In [193]:
print(np.sin(X)) # sinx
print(np.cos(X)) # sec 倒数
print(np.tan(X))
print(np.arcsin(np.log10(X[3:,:]))) # 定义域-1到1

[[ 0.2794155   0.70554033  0.95892427  0.97753012  0.7568025   0.35078323]
 [-0.14112001 -0.59847214 -0.90929743 -0.99749499 -0.84147098 -0.47942554]
 [ 0.          0.47942554  0.84147098  0.99749499  0.90929743  0.59847214]
 [ 0.14112001 -0.35078323 -0.7568025  -0.97753012 -0.95892427 -0.70554033]]
[[ 0.96017029  0.70866977  0.28366219 -0.2107958  -0.65364362 -0.93645669]
 [-0.9899925  -0.80114362 -0.41614684  0.0707372   0.54030231  0.87758256]
 [ 1.          0.87758256  0.54030231  0.0707372  -0.41614684 -0.80114362]
 [-0.9899925  -0.93645669 -0.65364362 -0.2107958   0.28366219  0.70866977]]
[[  0.29100619   0.99558405   3.38051501  -4.63733205  -1.15782128
   -0.37458564]
 [  0.14254654   0.7470223    2.18503986 -14.10141995  -1.55740772
   -0.54630249]
 [  0.           0.54630249   1.55740772  14.10141995  -2.18503986
   -0.7470223 ]
 [ -0.14254654   0.37458564   1.15782128   4.63733205  -3.38051501
   -0.99558405]]
[[0.49737616 0.57527798 0.64607859 0.71181948 0.77395623 0.833609

In [186]:
print(np.ceil(np.log10(X[3:,:]))) # 上取整
print(np.floor(np.log10(X[3:,:]))) # 下取整
print(np.round(X)) # 四舍五入

array([[1., 1., 1., 1., 1., 1.]])

## 二元运算

In [199]:
print(X+1)
print(np.add(X,1))
print(X-1)

[[-5.  -4.5 -4.  -3.5 -3.  -2.5]
 [-2.  -1.5 -1.  -0.5  0.   0.5]
 [ 1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5]]
[[-5.  -4.5 -4.  -3.5 -3.  -2.5]
 [-2.  -1.5 -1.  -0.5  0.   0.5]
 [ 1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5]]
[[-7.  -6.5 -6.  -5.5 -5.  -4.5]
 [-4.  -3.5 -3.  -2.5 -2.  -1.5]
 [-1.  -0.5  0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5  4.   4.5]]


In [204]:
print(X*2)
print(X/2)
print(2/X)

[[-12. -11. -10.  -9.  -8.  -7.]
 [ -6.  -5.  -4.  -3.  -2.  -1.]
 [  0.   1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.  11.]]
[[-3.   -2.75 -2.5  -2.25 -2.   -1.75]
 [-1.5  -1.25 -1.   -0.75 -0.5  -0.25]
 [ 0.    0.25  0.5   0.75  1.    1.25]
 [ 1.5   1.75  2.    2.25  2.5   2.75]]
[[-0.33333333 -0.36363636 -0.4        -0.44444444 -0.5        -0.57142857]
 [-0.66666667 -0.8        -1.         -1.33333333 -2.         -4.        ]
 [        inf  4.          2.          1.33333333  1.          0.8       ]
 [ 0.66666667  0.57142857  0.5         0.44444444  0.4         0.36363636]]


C:\Users\huangyingzhu\AppData\Local\Temp\ipykernel_17812\3544551358.py:3: RuntimeWarning: divide by zero encountered in divide
  print(2/X)


In [205]:
print(X//2) # 每个元素除以2，结果取整数部分
print(X%2) # 取余
print(X**3) # 幂

[[-3. -3. -3. -3. -2. -2.]
 [-2. -2. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  1.  1.]
 [ 1.  1.  2.  2.  2.  2.]]
[[0.  0.5 1.  1.5 0.  0.5]
 [1.  1.5 0.  0.5 1.  1.5]
 [0.  0.5 1.  1.5 0.  0.5]
 [1.  1.5 0.  0.5 1.  1.5]]
[[-2.16000e+02 -1.66375e+02 -1.25000e+02 -9.11250e+01 -6.40000e+01
  -4.28750e+01]
 [-2.70000e+01 -1.56250e+01 -8.00000e+00 -3.37500e+00 -1.00000e+00
  -1.25000e-01]
 [ 0.00000e+00  1.25000e-01  1.00000e+00  3.37500e+00  8.00000e+00
   1.56250e+01]
 [ 2.70000e+01  4.28750e+01  6.40000e+01  9.11250e+01  1.25000e+02
   1.66375e+02]]


## 矩阵运算

In [206]:
X = np.linspace(10,40,4).reshape(2,2)
Y = np.linspace(1,4,4).reshape(2,2)
print(X)
print(Y)

[[10. 20.]
 [30. 40.]]
[[1. 2.]
 [3. 4.]]


### 矩阵的加减乘除

In [207]:
print(X+Y)
print(X-Y)

[[11. 22.]
 [33. 44.]]
[[ 9. 18.]
 [27. 36.]]


In [208]:
print(X*Y) # 对应元素相乘
print(X.dot(Y)) # 矩阵的乘法

[[ 10.  40.]
 [ 90. 160.]]
[[ 70. 100.]
 [150. 220.]]


In [209]:
print(X/Y) # 对应元素相除

[[10. 10.]
 [10. 10.]]


### 矩阵的转置

In [210]:
# 转置运算 行列
print(X.T) 
print(np.transpose(X))

[[10. 30.]
 [20. 40.]]
[[10. 30.]
 [20. 40.]]


### 对应元素计算的补足

In [212]:
Z = np.linspace(1,4,4)
X + Z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [214]:
Z = np.linspace(1,4,2)
X, Z

(array([[10., 20.],
        [30., 40.]]),
 array([1., 4.]))

In [216]:
print(X + Z) # 补足
print(X * Z) # 补足

[[11. 24.]
 [31. 44.]]
[[ 10.  80.]
 [ 30. 160.]]


In [217]:
print(Z.dot(X)) #  矩阵乘法
print(X.dot(Z)) # 没有交换律

[130. 180.]
[ 90. 190.]


### 计算矩阵的逆

In [218]:
V = np.linalg.inv(X) # 求矩阵的逆np.linalg.inv()
V

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [219]:
print(X.dot(V)) # 验证矩阵的逆
print(V.dot(X)) # I 精度问题

[[1.0000000e+00 0.0000000e+00]
 [4.4408921e-16 1.0000000e+00]]
[[ 1.00000000e+00  4.44089210e-16]
 [-1.11022302e-16  1.00000000e+00]]


In [221]:
np.linalg.inv(np.arange(12).reshape(3,4)) # 非方阵 没有逆

LinAlgError: Last 2 dimensions of the array must be square

### 计算矩阵的行列式

In [222]:
np.linalg.det(X)

-200.0000000000001

### 计算矩阵的特征值特征向量

In [224]:
np.linalg.eig(X) # 计算矩阵 X 的特征值（eigenvalues）和对应的特征向量（eigenvectors）

(array([-3.72281323, 53.72281323]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

# nparr的统计计算