In [3]:
import torch
import torch.nn as nn

In [4]:
# 掩码
tensor = torch.arange(0, 16).view(4, 4)
print('origin tensor: \n{}\n'.format(tensor))

mask = torch.eye(4, dtype=torch.bool)
print('mask tensor: \n{}\n'.format(mask))

tensor = tensor.masked_fill(mask, 100)  # 掩码 遮
print('filled tensor: \n{}\n'.format(tensor))

origin tensor: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

mask tensor: 
tensor([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]])

filled tensor: 
tensor([[100,   1,   2,   3],
        [  4, 100,   6,   7],
        [  8,   9, 100,  11],
        [ 12,  13,  14, 100]])



In [9]:
# Dropout：一定概率地把一些值变成0 其余值做补偿变化
m = nn.Dropout(p=0.2)
input = torch.randn(20,16)
output = m(input)

print(input[0])
print(output[0])

tensor([ 0.0110, -0.8802,  0.6677,  0.0415, -0.0190, -0.9293, -0.6466, -0.9599,
        -0.2669, -0.2189,  1.8022, -1.8476,  0.6452,  0.5155,  1.8848, -0.2777])
tensor([ 0.0137, -1.1002,  0.8346,  0.0000, -0.0238, -0.0000, -0.8083, -1.1999,
        -0.3337, -0.2737,  2.2528, -2.3096,  0.8064,  0.6444,  2.3559, -0.3472])
