In [2]:
import torch
import torch.nn as nn

In [3]:
# 掩码
tensor = torch.arange(0, 16).view(4, 4)
print('origin tensor: \n{}\n'.format(tensor))

mask = torch.eye(4, dtype=torch.bool)
print('mask tensor: \n{}\n'.format(mask))

tensor = tensor.masked_fill(mask, 100)  # 掩码 遮
print('filled tensor: \n{}\n'.format(tensor))

origin tensor: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

mask tensor: 
tensor([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]])

filled tensor: 
tensor([[100,   1,   2,   3],
        [  4, 100,   6,   7],
        [  8,   9, 100,  11],
        [ 12,  13,  14, 100]])



In [4]:
# Dropout：一定概率地把一些值变成0 其余值做补偿变化
m = nn.Dropout(p=0.2)
input = torch.randn(20,16)
output = m(input)

print(input[0])
print(output[0])

tensor([ 0.9581, -1.6042,  0.4885,  1.4082, -1.2212, -1.5512, -0.4826, -1.0714,
         0.4663,  0.2002, -0.7232,  0.7105,  1.8909,  1.7211,  0.4246,  0.3275])
tensor([ 1.1976, -2.0052,  0.0000,  1.7602, -1.5265, -1.9390, -0.6032, -1.3392,
         0.5829,  0.2502, -0.9040,  0.8881,  2.3636,  2.1513,  0.5307,  0.4094])


In [11]:
# view squeeze transpose
a1 = torch.tensor([i for i in range(24)])
a2 = a1.view(2, 3,-1)
a3 = a2.view(-1)
a3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [5]:
# register_buffer 注册buffer 指定向量不再参与梯度下降
